[package]
name = "todo-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
clap = { version = "4.0.32", features = ["derive"] }
deadpool-postgres = "0.10.3"
env_logger = "0.10.0"
futures-util = "0.3.25"
log = "0.4.17"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
tokio = { version = "1.23.0", features = ["full"] }
tokio-postgres = "0.7.7"
auth-service-api = {version = "*", git = "https://github.com/innexgo/auth-service-api" }
derive_more = "0.99.17"
