[package]
name = "todoproxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
clap = { version = "4.1.8", features = ["derive"] }
deadpool-postgres = "0.10.5"
env_logger = "0.10.0"
futures-util = "0.3.27"
log = "0.4.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.94"
tokio = { version = "1.26.0", features = ["full"] }
tokio-postgres = "0.7.7"
auth-service-api = {version = "*", git = "https://github.com/innexgo/auth-service-api", features=["client"]}
todoproxy-api = {version = "*", git = "https://github.com/pimpale/todoproxy-api" }
derive_more = "0.99.17"
actix-ws = "0.2.5"
tokio-stream = { version = "0.1.12", features = ["sync"] }
rand = "0.8.5"
reqwest = "0.11.14"
